#!/usr/bin/env python3
"""Bake the Kenney CC0 sound effects into gavaga.

Reads the OGG files in assets/kenney/, decodes them to the exact format the
mixer runs at, and writes src/gv_sfx_pcm.h as C arrays.

Decoded and embedded rather than shipped and loaded, for the same reasons as
the art: SDL decodes WAV but not OGG, so playing them as-is would mean
SDL_mixer or a vorbis decoder, and the binary should stay one file you can copy
anywhere. Decoding at bake time costs nothing at runtime either - the mixer
gets plain 16-bit PCM at its own sample rate and never resamples.

Needs ffmpeg on PATH; nothing else beyond python3.

    python3 tools/make_sounds.py
"""
import os
import struct
import subprocess
import sys

RATE = 44100        # must match GV_SR in gv_audio.c
PEAK = 0.89         # normalise to just under full scale

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "assets", "kenney")

# (C name, source file, seconds cap, gain)
#
# The caps matter. sfx_laser1 is 1.2 seconds; the player can fire roughly three
# times a second, so untrimmed it would pile four copies on top of each other
# and turn into a drone. Everything is cut to the part that carries the event.
SOUNDS = [
    ("LASER1",     "sfx_laser1.ogg",     0.32, 0.80),
    ("LASER2",     "sfx_laser2.ogg",     0.34, 0.75),
    ("ZAP",        "sfx_zap.ogg",        0.55, 0.95),
    ("LOSE",       "sfx_lose.ogg",       0.70, 1.00),
    ("SHIELD_UP",  "sfx_shieldUp.ogg",   0.40, 0.90),
    ("SHIELD_DOWN","sfx_shieldDown.ogg", 0.50, 0.90),
    ("TWO_TONE",   "sfx_twoTone.ogg",    1.10, 0.85),
]

# GV_SFX_* -> sound name, or None to leave it to the synth. The pack has seven
# effects and the game raises fourteen events, so the rest stay synthesised;
# they are the ones with no plausible stand-in here.
MAPPING = [
    ("GV_SFX_NONE",          None),
    ("GV_SFX_SHOT",          "LASER1"),
    ("GV_SFX_ENEMY_BOOM",    "ZAP"),
    ("GV_SFX_FLAGSHIP_HIT",  "LASER2"),
    ("GV_SFX_FLAGSHIP_BOOM", None),
    ("GV_SFX_PLAYER_BOOM",   "LOSE"),
    ("GV_SFX_DIVE",          None),
    ("GV_SFX_BEAM",          None),
    ("GV_SFX_CAPTURED",      "SHIELD_DOWN"),
    ("GV_SFX_RESCUE",        "SHIELD_UP"),
    ("GV_SFX_EXTRA_LIFE",    "SHIELD_UP"),
    ("GV_SFX_STAGE",         "TWO_TONE"),
    ("GV_SFX_GAMEOVER",      None),
    ("GV_SFX_PERFECT",       None),
]


def decode(path, cap):
    """OGG -> mono signed 16-bit at RATE, trailing silence removed."""
    cmd = [
        "ffmpeg", "-v", "error", "-i", path,
        "-af", "silenceremove=stop_periods=-1:stop_threshold=-50dB:stop_silence=0.02",
        "-ac", "1", "-ar", str(RATE), "-t", str(cap),
        "-f", "s16le", "-",
    ]
    out = subprocess.run(cmd, capture_output=True, check=True).stdout
    n = len(out) // 2
    return list(struct.unpack(f"<{n}h", out[:n * 2]))


def normalise(samples, gain):
    peak = max((abs(s) for s in samples), default=0)
    if not peak:
        return samples
    scale = (PEAK * 32767.0 * gain) / peak
    return [max(-32768, min(32767, int(s * scale))) for s in samples]


def fade_tail(samples, ms=8):
    """A cut that lands mid-waveform clicks. Ramp the last few milliseconds."""
    n = min(len(samples), RATE * ms // 1000)
    for i in range(n):
        samples[len(samples) - n + i] = int(samples[len(samples) - n + i] * (1.0 - i / n))
    return samples


def main():
    if not os.path.exists(SRC):
        sys.exit(f"missing {SRC}")

    baked = []
    total = 0
    for name, fname, cap, gain in SOUNDS:
        path = os.path.join(SRC, fname)
        if not os.path.exists(path):
            sys.exit(f"missing source sound: {path}")
        pcm = fade_tail(normalise(decode(path, cap), gain))
        baked.append((name, fname, pcm))
        total += len(pcm)
        print(f"  {name:12s} {len(pcm):7d} samples  {len(pcm)/RATE:5.2f}s  <- {fname}")

    hdr = os.path.join(ROOT, "src", "gv_sfx_pcm.h")
    with open(hdr, "w") as f:
        f.write("// gv_sfx_pcm.h - GENERATED by tools/make_sounds.py, do not edit.\n"
                "//\n"
                "// Kenney's sound effects, decoded to the mixer's own format so nothing\n"
                "// resamples at runtime and no vorbis decoder has to be linked in.\n"
                "//\n"
                "// Sound: Space Shooter Redux by Kenney (kenney.nl), CC0. The sources and\n"
                "// the licence are in assets/kenney/.\n"
                "//\n"
                "// The pack has seven effects; the game raises fourteen events. The ones\n"
                "// with no entry here stay synthesised - see gv_audio.c.\n"
                "#ifndef GV_SFX_PCM_H\n#define GV_SFX_PCM_H\n\n"
                f"#define GV_PCM_RATE {RATE}\n\n")

        for name, fname, pcm in baked:
            f.write(f"// {fname}\nstatic const short GV_PCM_{name}[{len(pcm)}] = {{\n")
            for i in range(0, len(pcm), 16):
                f.write("    " + ",".join(str(v) for v in pcm[i:i + 16]) + ",\n")
            f.write("};\n\n")

        f.write("typedef struct { const short *pcm; int len; } gv_pcm_clip;\n\n"
                "// Indexed by GV_SFX_*; a null clip means synthesise it instead.\n"
                "static const gv_pcm_clip GV_PCM_FOR_SFX[] = {\n")
        for sfx, snd in MAPPING:
            if snd:
                f.write(f"    [{sfx}] = {{ GV_PCM_{snd}, (int)(sizeof GV_PCM_{snd} / sizeof(short)) }},\n")
            else:
                f.write(f"    [{sfx}] = {{ nullptr, 0 }},\n")
        f.write("};\n\n#endif // GV_SFX_PCM_H\n")

    size = os.path.getsize(hdr)
    covered = sum(1 for _, snd in MAPPING if snd)
    print(f"\n{len(baked)} clips, {total} samples ({total/RATE:.2f}s), "
          f"{total*2/1024:.0f} KB of PCM")
    print(f"{covered} of {len(MAPPING) - 1} game events covered; the rest stay synthesised")
    print(f"  {hdr}  ({size/1024:.0f} KB of source)")


if __name__ == "__main__":
    main()
