// gv_star.c - starfield generated by a hardware-style linear feedback shift
// register, the way early-80s arcade boards did it.
//
// The idea: clock a 16-bit LFSR once per pixel as a virtual beam sweeps the
// field. Whenever the register lands on a chosen pattern, that pixel is a
// star, and spare bits of the register pick its colour and blink group. The
// result is a field that looks random but is generated from a single 16-bit
// seed and is perfectly reproducible.
//
// The original clocked the register live during scanout. We do the sweep once
// at init and keep the hits in a fixed array - same distribution, and it costs
// nothing per frame.
#include "gv_star.h"

// x^16 + x^14 + x^13 + x^11 + 1, the classic maximal-length 16-bit polynomial
// (period 65535). In Galois form the tap mask is applied on shift-out.
#define GV_LFSR_TAPS 0xB400u

// A star is emitted when the low bits match. 9 bits -> roughly 1 pixel in 512,
// which over a 224x288 field lands around 120 stars.
#define GV_STAR_MASK  0x01FFu
#define GV_STAR_MATCH 0x01FFu

// Star colours. Mostly cool whites and blues with a few warm ones, so the
// field reads as depth rather than confetti.
static const SDL_Color GV_STAR_PALETTE[GV_STAR_COLORS] = {
    { 255, 255, 255, 255 },  // white
    { 200, 216, 255, 255 },  // pale blue
    { 128, 176, 255, 255 },  // blue
    { 255, 232, 160, 255 },  // warm white
    { 255, 160, 128, 255 },  // amber
    { 160, 255, 216, 255 },  // aqua
    { 216, 176, 255, 255 },  // violet
    { 176, 176, 200, 255 },  // dim grey-blue
};

static inline uint16_t lfsr_next(uint16_t r) {
    uint16_t lsb = r & 1u;
    r >>= 1;
    if (lsb) r ^= GV_LFSR_TAPS;
    return r;
}

void gv_star_init(gv_starfield *sf, uint16_t seed) {
    SDL_zerop(sf);
    sf->speed       = gv_fix_from_f(0.35f);
    sf->set_mask    = 0x3;      // two of the four groups lit to start
    sf->blink_timer = 0;
    sf->blink_phase = 0;

    uint16_t r = seed ? seed : 0xACE1u;   // 0 is the LFSR's dead state

    // Sweep the virtual field exactly once, clocking per pixel.
    for (int y = 0; y < GV_SCREEN_H && sf->count < GV_MAX_STARS; y++) {
        for (int x = 0; x < GV_SCREEN_W && sf->count < GV_MAX_STARS; x++) {
            r = lfsr_next(r);
            if ((r & GV_STAR_MASK) != GV_STAR_MATCH) continue;

            gv_star *s = &sf->stars[sf->count++];
            s->x     = (int16_t)x;
            s->y     = (int16_t)y;
            s->color = (uint8_t)((r >> 9) & 0x7);    // spare high bits
            s->set   = (uint8_t)((r >> 12) & 0x3);
        }
    }
}

void gv_star_set_speed(gv_starfield *sf, fix_t px_per_tick) {
    sf->speed = px_per_tick;
}

void gv_star_tick(gv_starfield *sf) {
    sf->scroll += sf->speed;

    const fix_t wrap = gv_fix(GV_SCREEN_H);
    if (sf->scroll >= wrap) sf->scroll -= wrap;
    else if (sf->scroll < 0) sf->scroll += wrap;

    // Rotate which blink groups are lit. Two lit at a time keeps the density
    // steady while individual stars wink in and out.
    if (++sf->blink_timer >= 24) {
        sf->blink_timer = 0;
        sf->blink_phase = (uint16_t)((sf->blink_phase + 1) & 0x3);
        static const uint8_t pattern[4] = { 0x3, 0x6, 0xC, 0x9 };
        sf->set_mask = pattern[sf->blink_phase];
    }
}

// Drawn colour-by-colour rather than star-by-star. A SetRenderDrawColor
// between every point defeats SDL's batching, which turned this into ~250
// draw calls a frame - fine on a desktop GPU, ruinous through a virtualised
// OpenGL driver where each call is a round trip to the host. Bucketing by
// palette entry makes it 8 of each, and the field is identical.
void gv_star_draw(const gv_starfield *sf, SDL_Renderer *ren) {
    static SDL_FPoint bucket[GV_STAR_COLORS][GV_MAX_STARS];
    int n[GV_STAR_COLORS] = { 0 };

    const int off = gv_unfix(sf->scroll);

    for (int i = 0; i < sf->count; i++) {
        const gv_star *s = &sf->stars[i];
        if (!(sf->set_mask & (1u << s->set))) continue;

        int y = s->y + off;
        if (y >= GV_SCREEN_H) y -= GV_SCREEN_H;
        else if (y < 0) y += GV_SCREEN_H;

        const int c = s->color % GV_STAR_COLORS;
        bucket[c][n[c]].x = (float)s->x;
        bucket[c][n[c]].y = (float)y;
        n[c]++;
    }

    for (int c = 0; c < GV_STAR_COLORS; c++) {
        if (n[c] == 0) continue;
        const SDL_Color col = GV_STAR_PALETTE[c];
        SDL_SetRenderDrawColor(ren, col.r, col.g, col.b, 255);
        SDL_RenderPoints(ren, bucket[c], n[c]);
    }
}
